# LAST EDIT: Tue Feb 17 14:33:21 2004 by Andreas Loebel (opt0.zib.de) 
# $Id: Makefile.light,v 1.1 2004/02/17 13:59:19 bzfloebe Exp $

ARCH = Linux
include ../../Makefile.arch.${ARCH}
include ../../Makefile.modules.light
include ../../Makefile.include
include ../../Makefile.cppflags
include ../../Makefile.libs


lib: light.a


light.a: $(LIGHT_MOD:%=%.d) $(LIGHT_MOD:%=%.o)
	$(AR) cr $@ $(LIGHT_MOD:%=%.o)
	ranlib $@


include ../../Makefile.rules
include $(LIGHT_MOD:%=%.d)
